DemoDB/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoDB.Models;

namespace DemoDB.Controllers
{
    public class CustomerController : Controller
    {
        DBSportStoreEntities db = new DBSportStoreEntities();
        // GET: Customer
        public ActionResult Index(string _name)
        {
            if (_name == null)
            {
                return View(db.Customers.ToList());
            }
            else
                return View(db.Customers.Where(s => s.NameCus.Contains(_name)).ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Customer cust)
        {
            try
            {
                db.Customers.Add(cust);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("error Create new");
            }
        }
        public ActionResult Details(int id)
        {
            return View(db.Customers.Where(s => s.IDCus == id).FirstOrDefault());
        }
        public ActionResult Edit(int id)
        {
            return View(db.Customers.Where(s => s.IDCus == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Edit(int id,Customer cust)
        {
            db.Entry(cust).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            return View(db.Customers.Where(s => s.IDCus == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Delete(int id, Customer cust)
        {
            try
            { cust=db.Customers.Where(s=>s.IDCus==id).FirstOrDefault();
                db.Customers.Remove(cust);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content(" this data is using in other table, Error Delete! ");
            }
        }
        

    }
}

DemoDB/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoDB.Models;
using PagedList;
using PagedList.Mvc;
namespace DemoDB.Controllers
{
    public class ProductController : Controller
    {
        DBSportStoreEntities database = new DBSportStoreEntities();
        // GET: Product
        public ActionResult SearchOption(double min=double.MinValue, double max=double.MaxValue)
        {
             var list=database.Products.Where(p=>(double)p.Price>=min && (double)p.Price<=max).ToList();
            return View(list);
        }
        public ActionResult Index(string category, int? page, double min=double.MinValue, double max=double.MaxValue)
        {
            int pageSize = 4;
            int pagNum = (page ?? 1);
            if (category == null)
            {
                var productList = database.Products.OrderByDescending(x => x.NamePro);
                return View(productList.ToPagedList(pagNum,pageSize));
            }
            else
            {
                var productList = database.Products.OrderByDescending(x => x.NamePro).Where(x => x.Category == category);
                return View(productList);
            }
        }
        public ActionResult Create()
        {
            List<Category> list = database.Categories.ToList();
            ViewBag.listCategory = new SelectList(list, "IDCate", "NameCate","");
            Product pro = new Product();
            return View(pro);
        }
        public ActionResult SelectCate()
        {
            Category se_cate = new Category();
            se_cate.ListCate = database.Categories.ToList<Category>();
            return PartialView(se_cate);
        }
        [HttpPost]
        public ActionResult Create(Product pro)
        { List<Category> list = database.Categories.ToList();
            try
            {
                if(pro.UploadImage!=null)
                {
                    string filename = Path.GetFileNameWithoutExtension(pro.UploadImage.FileName);
                    string extent = Path.GetExtension(pro.UploadImage.FileName);
                    filename = filename + extent;
                    pro.ImagePro = "~/Content/images/" + filename;
                    pro.UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Content/images/"), filename));
                }
                ViewBag.listCategory = new SelectList(list, "IDCate", "NameCate", 1);
                database.Products.Add(pro);
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DemoDB/Controllers/ShopingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoDB.Models;
namespace DemoDB.Controllers
{
    public class ShopingCartController : Controller
    {
        // GET: ShopingCart
        DBSportStoreEntities database = new DBSportStoreEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Showcart()
        {
            if (Session["Cart"] == null)
                return View("EmptyCart");
            Cart _cart = Session["Cart"] as Cart;
            return View(_cart);
        }
        public Cart GetCart()
        {
            Cart cart = Session["Cart"] as Cart;
            if(cart==null|| Session["Cart"]==null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }
        public ActionResult AddToCart(int id)
        {
            var _pro = database.Products.SingleOrDefault(s => s.ProductID == id);
            if(_pro!=null)
            {
                GetCart().Add_Product_Cart(_pro);
            }
            return RedirectToAction("ShowCart", "ShopingCart");
        }
        public ActionResult Update_Cart_Quantity(FormCollection form)
        {
            Cart cart = Session["Cart"] as Cart;
            int id_pro = int.Parse(form["idPro"]);
            int _quantity = int.Parse(form["CartQuantity"]);
            cart.Update_quantity(id_pro, _quantity);
            return RedirectToAction("ShowCart", "ShopingCart");
        }
        public ActionResult RemoveCart(int id)
        {
            Cart cart = Session["Cart"] as Cart;
            cart.Remove_CartItem(id);
            return RedirectToAction("ShowCart", "ShopingCart");
        }
        public PartialViewResult BagCart()
        {
            int total_quantity_item = 0;
            Cart cart = Session["Cart"] as Cart;
            if (cart != null)
                total_quantity_item = cart.Total_quantity();
            ViewBag.QuantityCart = total_quantity_item;
            return PartialView("BagCart");
        }
        public ActionResult CheckOut_Success()
        {
            return View();
        }
        public ActionResult CheckOut(FormCollection from)
        {
            try
            {
                Cart cart = Session["Cart"] as Cart;
                OrderPro _order = new OrderPro();
                _order.DateOrder = DateTime.Now;
                _order.AddressDeliverry = from["AddressDeliverry"];
                _order.IDCus = int.Parse(from["CodeCustomer"]);
                database.OrderProes.Add(_order);
                foreach(var item in cart.Items)
                {
                    OrderDetail _oder_detail = new OrderDetail();
                    _oder_detail.IDOrder = _order.ID;
                    _oder_detail.IDProduct = item._product.ProductID;
                    _oder_detail.UnitPrice = (double)item._product.Price;
                    _oder_detail.Quantity = item._quantity;
                    database.OrderDetails.Add(_oder_detail);
                    foreach(var p in database.Products.Where(s=>s.ProductID== _oder_detail.IDProduct))
                    {
                        var update_quan_pro = p.Quantity - item._quantity;
                        p.Quantity = update_quan_pro;
                    }
                }
                database.SaveChanges();
                cart.ClearCart();
                return RedirectToAction("CheckOut_Success", "ShopingCart");
            }catch
            {
                return Content(" Error checkout, Plesase check infomation of customer...thanks  ");
                
            }
        }
    }
}

DemoDB/Views/ShopingCart/AddToCart.cshtml
@{
    ViewBag.Title = "AddToCart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddToCart</h2>

DemoDB/Views/ShopingCart/BagCart.cshtml
<span style="color:red ;margin-left:-8px" class="badge">@ViewBag.QuantityCart</span>

DemoDB/Views/ShopingCart/CheckOut_Success.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CheckOut_Success</title>
</head>
<body style="text-align:center">
<h2>CheckOut Sucessful</h2>
    <h4>Orders of you had  sent to the shop. You will  receive goods in 2-3 days. Thanks. </h4>
    <a href="@Url.Action("Index","Product")">Continuos Shopping....</a>
</body>
</html>

DemoDB/Views/ShopingCart/EmptyCart.cshtml
<h2> Gio Hang</h2>
<a href="@Url.Action("Index","Product")">tiep tuc mua hang</a>
<table class="table">
    <thead>
        <tr>
            <th>ten san pham</th>
            <th>hinh san pham</th>
            <th>gia</th>
            <th>so luong</th>
            <th>thanh tien</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="6">
                chua co san pham nao..........
            </td>
        </tr>
    </tbody>
</table>

DemoDB/Views/ShopingCart/Showcart.cshtml
@model DemoDB.Models.Cart

@{
    ViewBag.Title = "Showcart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Gio Hang</h2>
<a href="@Url.Action("Index","Product")">tiep tuc mua hang</a>
@if(Model!=null)
            {
                <table calss="Table">
                    <thead>
                        <tr>
                            <th>ten san pham</th>
                            <th>hinh san pham</th>
                            <th>gia san pham</th>
                            <th>so luong</th>
                            <th> thanh tien</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var item in Model.Items)
                        {
                            decimal total = item._quantity * (decimal)item._product.Price.Value;
                            <tr>
                                <td>@Html.DisplayFor(model=>item._product.NamePro)</td>
                                <td><img src="@Url.Content(item._product.ImagePro)" height="50" width="50"/>"</td>
                                <td>@Html.DisplayFor(model=>item._product.Price)</td>
                                <td>
                                    @using (Html.BeginForm("Update_Cart_Quantity", "ShopingCart"))
                                    {
                                        <input type="hidden" value="@item._product.ProductID" name="idPro" />
                                        <input type="number" value="@item._quantity" name="CartQuantity" />
                                        <input type="submit" value="Update" />
                                    }
                                </td>
                                <td>@total</td>
                                <td>
                                    <a href="~/ShopingCart/RemoveCart/@item._product.ProductID"> Xoa</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="6" style=" text-align:right">tong tien: @Model.Total_money()</td>

                        </tr>
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="4">
                                @using (Html.BeginForm("CheckOut","ShopingCart"))
                                  {
                                <table style="border-collapse:separate;border-spacing:5px">
                                    <tr>
                                        <td>code Customer: </td>
                                        <td> <input type="number" name="CodeCustomer" required</td>
                                    </tr>
                                    <tr>
                                        <td>AddressDelivery </td>
                                        <td> <input type="text" name="AddressDelivery" required</td>
                                    </tr>
                                    <tr>
                                        <td>AddressDelivery </td>
                                        <td> <input type="submit" name="CheckOut" class="btn btn-success" />
                                        <a href="@Url.Action("Create","Customer")" class="btn btn-success">Resister</a>
                                        </td>
                                        
                                    </tr>
                                </table>
                                  }
                            </td>
                        </tr>
                    </tfoot>
                </table>
            }
            else
            {
                @Html.Partial("EmptyCart")
            }